name: uniprbooks

services: 
  front:
    image: httpd:2.4
    volumes:
      - type: bind
        source: src/frontend
        target: /usr/local/apache2/htdocs/
        read_only: true
      - ./docker/front/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    ports:
      - "8080:80"

  back:
    build:
      context: docker/back
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: src/backend
        target: /var/www/html
    ports:
      - "8081:80"
    environment:
      ALLOWED_ORIGIN: "http://localhost:8080"
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    container_name: uniprbooks-db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data:
